### ISSUE TITLE
Display blocked status better

### ISSUE THREAD

**Issue by banunkers** [MTBorg/M7011E_lab#179]
Blocked status should be displayed better on prosumer dashboard and prosumer-summary

**Comment by MTBorg** [comment]
Better how?

**Comment by banunkers** [comment]
Nvm I didn't see that it was updated

**Comment by banunkers** [comment]
I might try and add a symbol with the text as well so you notice it easier as a prosumer

**Comment by MTBorg** [comment]
Nevermind, i agree, i thought you read prosumer-overview.
